# Generated by Django 6.0.5 on 2026-05-29 16:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guide_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('organisation', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, choices=[('private-landlord', 'Private landlord'), ('housing-association', 'Housing association / council'), ('surveyor', 'Surveyor / consultant'), ('letting-agent', 'Letting agent'), ('other', 'Other')], max_length=50)),
                ('properties_range', models.CharField(blank=True, max_length=50)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('download_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_expires_at', models.DateTimeField()),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='leads_lead_email_f663dc_idx'), models.Index(fields=['download_token'], name='leads_lead_downloa_3e5a5d_idx'), models.Index(fields=['created_at'], name='leads_lead_created_302c6d_idx')],
            },
        ),
    ]
